language: go
go:
- 1.9.x
install: make bootstrap
branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
deploy:
- provider: script
  script: make release
  skip_cleanup: true
  on:
    tags: true
    repo: manifoldco/terraform-provider-manifold
env:
  global:
  - MANIFOLD_TEAM=manifold-integration-ci
  - TF_ACC=true
  - AWS_REGION=us-east-1
  # MANIFOLD_API_TOKEN
  - secure: TtOkVm709CaU+NPMB8nmi1T0Q4wcdzU8PHVyTKGbPgaPU4KnIO0mUTHRhulsqhI667BeZ7AUVilT9zhaotyS7Fa9RPJ6iEi5oZo/juP3eTk/3CF5Vd+K35eNzQE5jnONFvIPL3CHEaGpTfuXJ1Iq+i7mx+f992WVcPLbF3WyosWoDCBg+oLAXGzrKUz1UW40i8ERX2DGqxc4mdwcGYRa0UlfmfpP62bRAkt0mHfLHk2nqjFOnR3qwh5GmpSMcuHaJ8le7kpCjUNAjN/dYWNSmJ0ghmWXJ+iclq/+VqtOYiW1Bk+tsxv9ehS5QxKBz1GKm6m4z9o0eTXCYZlwYAhePf1E1xQ3CklvSdT+dArdRaVrImywLKOwgkxrF8TvHj/jEKKkUXWRnRR7MyfJ2M7PSSCIIoOddzUpL1Sf5Y3F1HGqYx6k5xTrWWvToXD1jvLf17RjdN0YyYldiYsxlsABoGLDXb0LdtUU2ICm3yhfyqrCq7FLmfNQ9JJMHqryr806/B2Xrrmr5R62G45AUkv22hIcK1KHJ1FvNWt33BdqpO0DM+weie7Y02OICJE6d1AzzBBF1bDJUdPyW5TTVbcnSA7XobVsjFbOqxFki8MQzqk/h4CSzfPuti4TKxkOILouTgEiMVX0Fw7i9+mMZ3T3VK6C+0k/F/RtwWZJ0ieMN8s=
  # AWS_ACCESS_KEY_ID
  - secure: D788IIYKZK0Azj6vqFwCnMbJW/lEUsP7K/P8Avq7B2kN1i07PaLIPeFcL8+/VlnNC3IEXeqWP6x1ONGkFre3rLN++YXhoFuvXOt+4GVOMOURDnm/sedmnSOnvWPT677TSmlWMyGXB97hhHI/rVgJ2A10dMGUZQKYnKrYtUsKlWl1dmbqhfMJ4F/VJawhBMalasdM6JF7TRojUO3U04wa0AXupcHqJO5DnSby7rFl6D95+At3QVpfI97L6jwY8z2ea5d+o/3nTltzjOCwFXQbfD8mIbRL/1hFX8uC1Mq6JkdJLUpPHGydO1bV9c/WPVGwd/9HQSjOJqpsVfkTqZogU9ifMvxNQMDu4YitTFXov1kFm7tZIxXhFpHsJPm7xxlRn2nDlDjkECLHG42XddVKVRMtfKFS715ufxYXMI+c0b9XmOXYCAsozgBLGjC2miQwg7foQoAmz7XIwg6lxYkOkAEnC3BtVK0fYI0Ezcbbk+geX5gIktr7TXD6VgCWo8eq9xQVqQXopPU03f6qAOfNZzexWJR/O55ST7xnHXg5mrnj3rFoW6QOjydkPtdey0UvgUNGCWJmCyqSoNemSxRx1eWMOLYA0SVnfEDY9l1ZcQ5KjnVvDsuLbpnawSTx2go4LakWP/owAiwpXmfZ+6oEnw5nFaCpK592HswMInDgXtQ=
  # AWS_SECRET_ACCESS_KEY
  - secure: Sxx4drDGcl+u8LMh3I8g4qpCxYelSXHuwRsFSbQhp9C+eD0He6gorA8N5IFGBU1nYQfDUF+BhudKs8SRLhC4OL7OyGVtExFq35k7NDMR0ierJH7seKWbCqpJ421p+M0+3TVER/aNnlP/ZtlcvkCJE4sFbRnzaZVIeT++Mh01eVaaTSjG9YzAexo/ski/r9DNQVEHJhmj9FQdepES/r8a39nTEshiD/CimVbTj57lTAl56+DuERsQ9T8k+bjhAlaTqmOOs4v9HXDP09OgEAbLAgxh4f0YscNIFMy9LQR/FyrOfzWR6CjP3OeS5fr0dqqLuf/cGQ01zfmno59aKCJulrw3kKEW9Jksu5xRhHeC4K2KlRRIuTSHKLKVSA3QWf1UjdZYmhhQIrH2ea7nnBp7FWJ9DTLJVdqPmvdkavG5ubHhoDFm924d8v1yka/qu7JCCWcZLJWdZa6Jw41Bi2z/w3nbdBc7NQaio4ZH+cR+lnTI/jYsMteulUGV9QpdD5DGmj3QFv4SO6TJIw34g9r0cZb2spdbH2g1ud3WAg2sjN+mHJkHhJFZf4rxbCHc75QcXECD37jBhFQMXTI9nGJ7L2SZ4sSPCVwyOhZIFvzE2NF9D9QxtKedZQCb+FeYYi/BVAKf0mhYWkPqNCHRKu1w3zdQUpiNLGsGHBOdey41M1s=
  # GITHUB_TOKEN
  - secure: KEeEOrN5AnypX5pAXkz8AfvaXC/sVTikU77FKxdV+VVOXKxNGgsbIlbnek8fufWTpAxPoLWjFsde05Cc3EaSuoaXfUy8Yv8Q+smBfjk9n0aVbEB+pOEy6VHnd+zzt5k2LwtKxlxYZaecdROT3nReyHETLky0cOoho06DtW6/lgqGvoiyzKqxLf7XanAbnE5eMFmymC40akz1w9DFEM2kZz9JyGOwVJnjBNHEE5p/Jx9RV36TY50losppTqzf3iuoDYDiI5UGS6puIzw5QJFQrX42IJl3LU3oilDrNTvwsoJH7eg4iiI/PYuNRcCwaNFNKteY27FWog+zzQeq9x5AsMiqfAlENDsSfmqx8EE+hCBFcr/FBr1Nsx4H2n802tCFG67bRS7ExkzWcZQKXHKyApSHFMmSVf5NCEGoiArYVgHYhsT1ZJK6FHghd0y4Dnv9SIQwtZ+zLKjixYy4+V9OWy5sA6t2c2wG8N/GBOlNJmJyKQs3iwUJhXqFfzwV4QhS3DOu8XC9bA99r97/hdWC9OW+qzy1FqWW6DwCQOp6YU/wcuu8sq0Vg6hkNVm52ZIgRzqCCP+aLtUZ1cNPNdnAyEXqwNQeNFNO8HlgrWjP7RZKVjlLnqdXJiA1CdisjYgIJ5p7DyLr4KSVx2kUy8a6ivUMIgxhPWjVlZ05IKV7CuA=
